=== SignalK/specification/1.8.4/schemas/messages/subscribe.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://signalk.org/specification/1.8.4/schemas/messages/subscribe.json#",
  "title": "SignalK SUBSCRIBE message schema",
  "type": "object",
  "description": "A message to allow a client to subscribe for data updates from a signalk server",
  "properties": {
    "context": {
      "id": "context",
      "type": "string",
      "title": "Context Path.",
      "description": "The root path for all subsequent paths, usually a vessel's path.",
      "name": "context",
      "example": "vessels.230099999"
    },

    "websocket.connectionkey": {
      "id": "websocket.connectionkey",
      "type": "string",
      "title": "Websocket.connectionkey.",
      "description": "An optional session key that is used in STOMP and MQTT messages where there are no session facilities",
      "name": "websocket.connectionkey",
      "example": "d2f691ac-a5ed-4cb7-b361-9072a24ce6bc"
    },

    "reply-to": {
      "id": "reply-to",
      "type": "string",
      "title": "Reply-to.",
      "description": "A reply queue that is used in STOMP and MQTT messages where there are no session facilities.",
      "name": "reply-to",
      "example": "signalk.3202a939-1681-4a74-ad4b-3a90212e4f33.vessels.motu.navigation"
    },

    "subscribe": {
      "id": "subscribe",
      "type": "array",
      "title": "Subscribe.",
      "description": "An array of paths to subscribe to, with optional criteria",
      "name": "subscribe",
      "items": [
        {
          "type": "object",
          "title": "Path object.",
          "description": "A path object with optional criteria to control output",
          "properties": {
            "path": {
              "id": "path",
              "type": "string",
              "title": "Path.",
              "description": "The path to subscribe to.",
              "name": "path",
              "example": "navigation.speedThroughWater"
            },

            "period": {
              "id": "period",
              "type": "integer",
              "title": "Period.",
              "description": "The subscription will be sent every period millisecs.",
              "name": "period",
              "default": 1000
            },

            "format": {
              "id": "format",
              "type": "string",
              "title": "Format.",
              "description": "The signal K format to use (full/delta) for the message.",
              "name": "format",
              "default": "delta"
            },

            "policy": {
              "id": "policy",
              "type": "string",
              "title": "Policy schema.",
              "description": "The policy for sending messages (instant/ideal/fixed).",
              "name": "policy",
              "default": "ideal"
            },
            
            "minPeriod": {
              "id": "minPeriod",
              "type": "integer",
              "title": "MinPeriod.",
              "description": "If policy=immediate or ideal, consequetive messages will be buffered until minPeriod has expired so the reciever is not swamped.",
              "name": "minPeriod",
              "default": 200
            }
          }
        }
      ]
    }
  },

  "required": [
    "context",
    "subscribe"
  ]
}

=== SignalK/specification/samples/subscribe/signalk-subscribe-mqtt.json
{
    "context": "vessels.self",
    "websocket.connectionkey":"d2f691ac-a5ed-4cb7-b361-9072a24ce6bc",
    "reply-to":"signalk.3202a939-1681-4a74-ad4b-3a90212e4f33.vessels.self.navigation",
    "subscribe": [
        {
                    "path": "navigation.speedThroughWater",
                    "period": 1000,
                    "format": "delta",
                    "policy": "ideal",
                    "minPeriod": 200
                },
         {
                    "path": "navigation.logTrip",
                    "period": 10000
                }
        ]
}
