=== SignalK/specification/schemas/signalk.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://signalk.org/specification/1.8.4/schemas/signalk.json#",
  "title": "SignalK",
  "description": "Root schema of Signal K. Contains the list of vessels plus a reference to the local boat (also contained in the vessels list).",
  "required": [
    "version",
    "self"
  ],
  "anyOf": [
    {
      "required": [
        "vessels"
      ]
    },
    {
      "required": [
        "aircraft"
      ]
    },
    {
      "required": [
        "aton"
      ]
    },
    {
      "required": [
        "sar"
      ]
    }
  ],
  "properties": {
    "self": {
      "type": "string",
      "description": "This holds the context (prefix + UUID, MMSI or URL in dot notation) of the server's self object.",
      "example": "vessels.urn:mrn:signalk:uuid:6b0e776f-811a-4b35-980e-b93405371bc5"
    },
    "vessels": {
      "type": "object",
      "description": "A wrapper object for vessel objects, each describing vessels in range, including this vessel.",
      "patternProperties": {
        "(^urn:mrn:(imo:mmsi:[2-7][0-9]{8}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|^(http(s?):.*|mailto:.*|tel:(\\+?)[0-9]{4,})$": {
          "description": "This regex pattern is used for validation of an MMSI or Signal K UUID identifier for the vessel. Examples: urn:mrn:imo:mmsi:230099999 urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
          "$ref": "vessel.json#"
        }
      },
      "additionalProperties": false
    },
    "aircraft": {
      "type": "object",
      "description": "A wrapper object for aircraft, primarily intended for SAR aircraft in relation to marine search and rescue. For clarity about seaplanes etc, if it CAN fly, its an aircraft.",
      "patternProperties": {
        "(^urn:mrn:(imo:mmsi:1[0-9]{8}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|^(http(s?):.*|mailto:.*|tel:(\\+?)[0-9]{4,})$": {
          "description": "This regex pattern is used for validation of an MMSI or Signal K UUID identifier for the aircraft. Examples: urn:mrn:imo:mmsi:111099999 urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
          "$ref": "aircraft.json#"
        }
      },
      "additionalProperties": false
    },
    "aton": {
      "type": "object",
      "description": "A wrapper object for Aids to Navigation (aton's)",
      "patternProperties": {
        "(^urn:mrn:(imo:mmsi:99[0-9]{7}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|^(http(s?):.*|mailto:.*|tel:(\\+?)[0-9]{4,})$": {
          "description": "This regex pattern is used for validation of an MMSI or Signal K UUID identifier for the aid to navigation. Examples: urn:mrn:imo:mmsi:991099999 urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
          "$ref": "aton.json#"
        }
      },
      "additionalProperties": false
    },
    "sar": {
      "type": "object",
      "description": "A wrapper object for Search And Rescue (SAR) MMSI's usied in transponders. MOB, EPIRBS etc",
      "patternProperties": {
        "(^urn:mrn:(imo:mmsi:97[0-9]{7}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|^(http(s?):.*|mailto:.*|tel:(\\+?)[0-9]{4,})$": {
          "description": "This regex pattern is used for validation of an MMSI or Signal K UUID identifier for the aid to navigation. Examples: urn:mrn:imo:mmsi:972099999 urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
          "$ref": "sar.json#"
        }
      },
      "additionalProperties": false
    },    
    "sources": {
      "description": "Metadata about the data sources; physical interface, address, protocol, etc.",
      "$ref": "groups/sources.json#"
    },
    "resources": {
      "description": "Resources to aid in navigation and operation of the vessel including waypoints, routes, notes, etc.",
      "$ref": "groups/resources.json#"
    },
    "version": {
      "description": "Version of the schema and APIs that this data is using in Canonical format i.e. V1.5.0.",
      "$ref": "definitions.json#/definitions/version"
    }
  }
}

=== SignalK/specification/samples/full/docs-data_model.json
{
  "version": "1.0.0",
  "self": "urn:mrn:signalk:uuid:705f5f1a-efaf-44aa-9cb8-a0fd6305567c",
  "vessels": {
    "urn:mrn:signalk:uuid:705f5f1a-efaf-44aa-9cb8-a0fd6305567c": {
      "navigation": {
        "speedOverGround": {
          "value": 4.32693662,
          "$source": "ttyUSB0.GP",
          "sentence": "RMC",
          "timestamp": "2017-05-16T05:15:50.007Z"
        },
        "position": {
          "value": {
            "altitude": 0.0,
            "latitude": 37.81479,
            "longitude": -122.44880152
          },
          "$source": "ttyUSB0.GP",
          "sentence": "RMC",
          "timestamp": "2017-05-16T05:15:50.007Z"
        },
        "headingMagnetic": {
          "value": 5.55014702,
          "$source": "ttyUSB0.II",
          "sentence": "HDM",
          "timestamp": "2017-05-16T05:15:54.006Z"
        }
      },
      "name": "Motu",
      "uuid": "urn:mrn:signalk:uuid:705f5f1a-efaf-44aa-9cb8-a0fd6305567c"
    }
  },
  "sources": {
    "ttyUSB0": {
      "label": "ttyUSB0",
      "type": "NMEA0183",
      "GP": {
        "talker": "GP",
        "sentences": {
          "RMC": "2017-04-03T06:14:04.451Z"
        }
      },
      "II": {
        "talker": "II",
        "sentences": {
          "HDM": "2017-05-16T05:15:54.006Z"
        }
      }
    }
  }
}

=== SignalK/specification/test/data/full-valid/lux-N2K.json
{
  "vessels": {
    "urn:mrn:imo:mmsi:230099999": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
      "mmsi": "230099999",
      "environment": {
        "outside": {
          "illuminance": {
            "value": 20000,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          }
        }
      }
    }
  },
  "sources": {
    "N2K-1": {
      "36": {
        "n2k": {
          "src": "36",
          "pgns": {
            "130312": "2017-01-25T00:03:05.056Z"
          }
        }
      },
      "label": "",
      "type": "NMEA2000"
    }
  },
  "version": "1.0.0",
  "self": "vessels.urn:mrn:imo:mmsi:230099999"
}

=== SignalK/specification/test/data/full-valid/resources-with position ref.json
{
  "vessels": {
    "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
      "navigation": {
        "position": {
          "timestamp": "2015-03-06T16:57:53.643Z",
          "$source": "nmea2.II",
          "sentence": "RMC",
          "value": {
            "longitude": 173.1693,
            "latitude": -41.156426,
            "altitude": 0
          }
        },
        "anchor": {
          "position": {
            "timestamp": "2015-03-06T16:57:53.643Z",
            "$source": "nmea2.II",
            "sentence": "RMC",
            "value": {
              "longitude": 173.1693,
              "latitude": -41.156426,
              "altitude": 0
            }
          },
          "currentRadius": {
            "timestamp": "2015-03-06T16:57:53.643Z",
            "$source": "self",
            "value": 10
          },
          "currentRadius": {
            "timestamp": "2015-03-06T16:57:53.643Z",
            "$source": "self",
            "value": 50
          }
        }
      }
    }
  },

  "resources": {
    "regions": {
      "urn:mrn:signalk:uuid:c0d79335-4e25-4245-8892-54e8ccc8021d": {
        "geohash": "rbejg:HugeFishFarm",
        "feature": {
          "type": "Feature",
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [-173.15, -41.155],
                [-173.15, -41.157],
                [-173.17, -41.157],
                [-173.17, -41.155],
                [-173.15, -41.155]
              ]
            ]
          },
          "properties": {
            "name": "Huge fish farm"
          }
        },
        "timestamp": "2015-03-06T16:57:53.643Z",
        "source": {
          "label": "region",
          "type": "manual"
        }
      }
    },
    "waypoints": {
      "urn:mrn:signalk:uuid:c0d79335-4e25-4248-8892-54e8ccc8021a": {
        "position": {
          "timestamp": "2015-03-06T16:57:53.643Z",
          "$source": "self",
          "value": {
            "longitude": 173.17,
            "latitude": -41.157,
            "altitude": 0
          }
        },
        "feature": {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [173.17, -41.157]
          },
          "properties": {
            "displayName": "My cool waypoint",
            "lastVisit": 23456789
          }
        }
      },
      "urn:mrn:signalk:uuid:c0d79335-4e25-4248-8892-54e8ccc8021c": {
        "position": {
          "timestamp": "2015-03-06T16:57:53.643Z",
          "$source": "self",
          "value": {
            "longitude": 173.13,
            "latitude": -41.15,
            "altitude": 0
          }
        },
        "feature": {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [173.13, -41.15]
          },
          "properties": {
            "displayName": "My cool waypoint",
            "lastVisit": 23456789
          }
        }
      }
    },

    "routes": {
      "urn:mrn:signalk:uuid:c0d79335-4e25-4248-8893-54e8ccc8021d": {
        "name": "Nelson to Abel Tasman Park",
        "description": "From Nelson Cut to just off Fishermans Island",
        "distance": 23.4,
        "start": "urn:mrn:signalk:uuid:c0d79335-4e25-4248-8892-54e8ccc8021d",
        "end": "urn:mrn:signalk:uuid:c0d79335-4e25-4248-8892-54e8ccc8021c",
        "feature": {
          "type": "Feature",
          "geometry": {
            "type": "LineString",
            "coordinates": [
              [173.17, -41.157],
              [173.15, -41.156],
              [173.13, -41.15]
            ]
          },
          "properties": {
            "popupContent": "Follow this route at your own peril...",
            "underConstruction": true
          }
        }
      }
    }
  },
  "version": "1.0.0",
  "self": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d"
}

=== SignalK/specification/test/data/multiple-values.json
{
  "vessels": {
    "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
      "navigation": {
        "courseOverGroundMagnetic": {
          "value": 3.615624078431453,
          "$source": "nmea2.II",
          "timestamp": "2017-03-04T14:58:48.000Z",
          "sentence": "VTG",
          "values": {
            "nmea1.II": {
              "value": 3.6376152270065814,
              "sentence": "VTG",
              "timestamp": "2017-03-04T14:58:47.000Z"
            },
            "nmea2.II": {
              "value": 3.615624078431453,
              "timestamp": "2017-03-04T14:58:48.000Z",
              "sentence": "VTG"
            }
          }
        }
      }
    }
  },
  "self": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
  "version": "0.1.0",
  "sources": {
    "nmea1": {
      "label": "nmea1",
      "type": "NMEA0183",
      "II": {
        "talker": "II",
        "sentences": {
          "VTG": "2017-03-04T14:58:47.000Z"
        }
      }
    },
    "nmea2": {
      "label": "nmea2",
      "type": "NMEA0183",
      "II": {
        "talker": "II",
        "sentences": {
          "VTG": "2017-03-04T14:58:48.000Z"
        }
      }
    }
  }
}

=== SignalK/specification/test/data/full-valid/sources-multiple sources for same path.json
{
  "vessels": {
    "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
      "environment": {
        "current": {
          "value": {
            "setTrue": 58.9,
            "drift": 0.28
          },
          "timestamp": "2014-08-15T18:00:00.755Z",
          "pgn": 130577,
          "$source": "sourceLabel1.160",
          "values": {
            "sourceLabel1.160": {
              "value": {
                "setTrue": 58.9,
                "drift": 0.28
              },
              "timestamp": "2014-08-15T18:00:00.755Z",
              "pgn": 130577
            },
            "sourceLabel2.166": {
              "value": {
                "setTrue": 52.2,
                "drift": 0.33
              },
              "timestamp": "2014-08-15T17:59:00.666Z",
              "pgn": 130577
            }
          }
        }
      },
      "navigation": {
        "attitude": {
          "value": {
            "yaw": 0.222,
            "pitch": 0.464,
            "roll": -2.496
          },
          "$source": "n2k1.204",
          "timestamp": "2013-10-08T15:47:28.263Z",
          "pgn": 127257,
          "values": {
            "n2k1.204": {
              "value": {
                "yaw": 0.222,
                "pitch": 0.464,
                "roll": -2.496
              },
              "timestamp": "2013-10-08T15:47:28.263Z",
              "pgn": 127257
            },
            "n2k1.222": {
              "value": {
                "yaw": 0.221,
                "pitch": 0.460,
                "roll": -2.490
              },
              "timestamp": "2013-10-08T15:47:27.263Z",
              "pgn": 127257
            }
          }
        },
        "courseOverGroundMagnetic": {
          "value": 3.615624078431453,
          "$source": "nmea2.II",
          "timestamp": "2017-03-04T14:58:48.000Z",
          "sentence": "VTG",
          "values": {
            "nmea1.II": {
              "value": 3.6376152270065814,
              "sentence": "VTG",
              "timestamp": "2017-03-04T14:58:47.000Z"
            },
            "nmea2.II": {
              "value": 3.615624078431453,
              "timestamp": "2017-03-04T14:58:48.000Z",
              "sentence": "VTG"
            }
          }
        },
        "closestApproach": {
          "value": {
            "distance": 250,
            "timeTo": 45
          },
          "$source": "foo.bar",
          "timestamp": "2014-08-15T19:00:15.404Z",
          "values": {
            "foo.bar": {
              "value": {
                "distance": 250,
                "timeTo": 45
              },
              "timestamp": "2014-08-15T19:00:15.404Z"
            },
            "foo.baz": {
              "value": {
                "distance": 251,
                "timeTo": 46
              },
              "timestamp": "2014-08-15T19:00:14.404Z"
            }
          }
        },
        "position": {
          "timestamp": "2015-03-06T16:57:53.643Z",
          "$source": "nmea1.II",
          "sentence": "GGL",
          "value": {
            "longitude": 173.1693,
            "latitude": -41.156426
          },
          "values": {
            "nmea1.II": {
              "timestamp": "2015-03-06T16:57:53.643Z",
              "sentence": "GGL",
              "value": {
                "longitude": 173.1693,
                "latitude": -41.156426
              }
            },
            "nmea2.II": {
              "timestamp": "2015-03-06T16:57:52.643Z",
              "sentence": "GGL",
              "value": {
                "longitude": 173.1692,
                "latitude": -41.156426
              }
            }
          }
        }
      }
    }
  },
  "self": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
  "version": "0.1.0",
  "sources": {
    "nmea1": {
      "label": "nmea1",
      "type": "NMEA0183",
      "II": {
        "talker": "II",
        "sentences": {
          "VTG": "2017-03-04T14:58:47.000Z"
        }
      }
    },
    "nmea2": {
      "label": "nmea2",
      "type": "NMEA0183",
      "II": {
        "talker": "II",
        "sentences": {
          "VTG": "2017-03-04T14:58:48.000Z"
        }
      }
    }
  }
}

=== SignalK/specification/test/data/full-valid/temperatures-sample.json
{
  "vessels": {
    "urn:mrn:imo:mmsi:230099999": {
      "uuid": "urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d",
      "mmsi": "230099999",
      "environment": {
        "water": {
          "temperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          }
        },
        "outside": {
          "temperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          },
          "dewPointTemperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          },
          "apparentWindChillTemperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          },
          "theoreticalWindChillTemperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          },
          "heatIndexTemperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          }
        },
        "inside": {
          "temperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          },
          "engineRoom": {
            "temperature": {
              "value": 0,
              "$source": ".36.0",
              "timestamp": "2017-01-24T23:59:01Z",
              "pgn": 130312
            }
          },
          "mainCabin": {
            "temperature": {
              "value": 0,
              "$source": ".36.0",
              "timestamp": "2017-01-24T23:59:01Z",
              "pgn": 130312
            }
          },
          "refrigerator": {
            "temperature": {
              "value": 0,
              "$source": ".36.0",
              "timestamp": "2017-01-24T23:59:01Z",
              "pgn": 130312
            }
          },
          "heating": {
            "temperature": {
              "value": 0,
              "$source": ".36.0",
              "timestamp": "2017-01-24T23:59:01Z",
              "pgn": 130312
            }
          },
          "freezer": {
            "temperature": {
              "value": 0,
              "$source": ".36.0",
              "timestamp": "2017-01-24T23:59:01Z",
              "pgn": 130312
            }
          }
        }
      },
      "propulsion": {
        "exhaust": {
          "temperature": {
            "value": 0,
            "$source": ".36.0",
            "timestamp": "2017-01-24T23:59:01Z",
            "pgn": 130312
          }
        }
      }
    }
  },
  "sources": {
    "N2K-1": {
      "36": {
        "label": "",
        "type": "NMEA2000",
        "0": {},
        "n2k": {
          "src": "36",
          "pgns": {
            "130312": "2017-01-25T00:03:05.056Z"
          }
        }
      }
    }
  },
  "version": "1.0.0",
  "self": "urn:mrn:imo:mmsi:230099999"
}

=== SignalK/specification/samples/full/0183-RMC-full.json
{ "self":"urn:mrn:imo:mmsi:366982330",
  "vessels": {
    "urn:mrn:imo:mmsi:366982330": {
      "mmsi": "366982330",
      "navigation": {
        "position": {
          "timestamp": "2015-03-06T16:57:53.643Z",
          "value": {
            "longitude": 173.1693,
            "latitude": -41.156426,
            "altitude": 0
          },
          "$source": "sources.gps_0183_RMC",
          "_attr": {
            "_mode": 644,
            "_owner": "self",
            "_group": "self"
          }
        },
        "courseOverGroundTrue": {
          "meta": {
            "zones": [
              {
                "lower": 260,
                "upper": 360,
                "state": "alarm"
              },
              {
                "lower": 220,
                "upper": 230,
                "state": "warn"
              },
              {
                "lower": 0,
                "upper": 220,
                "state": "alarm"
              },
              {
                "lower": 220,
                "upper": 260,
                "state": "normal"
              }
            ],
            "shortName": "COG",
            "alarmMethod": [
              "sound"
            ],
            "warnMethod": [
              "visual"
            ],
            "displayName": "COG (True)"
          },
          "timestamp": "2015-03-06T16:57:53.643Z",
          "$source": "sources.gps_0183_RMC",
          "_attr": {
            "_mode": 644,
            "_owner": "self",
            "_group": "self"
          },
          "value": 245.69
        }
      }
    }
  },
  "sources": {
    "gps_0183_RMC": {
      "timestamp": "2015-03-06T16:57:53.643Z",
      "src": "$GPRMC,033025.000,A,4115.6426,S,17316.9300,E,0.05,245.69,090113,,*15",
      "bus": "/dev/ttyUSB1"
    },
    "_attr": {
      "_mode": 644,
      "_owner": "self",
      "_group": "self"
    }
  },
  "version": "0.1.0"
}

=== SignalK/specification/test/data/full-valid/ais.json
{
  "vessels": {
    "urn:mrn:imo:mmsi:246326000": {
      "mmsi": "246326000",
      "name": "UTGERDINA",
      "design": {
        "length": {
          "meta": {
            "description": "The various lengths of the vessel"
          },
          "value": {
            "overall": 641
          },
          "$source": "DUMMY_LABEL.AI",
          "timestamp": "2020-02-08T09:48:58.219Z",
          "sentence": "VDM"
        },
        "beam": {
          "meta": {
            "units": "m",
            "description": "Beam length"
          },
          "value": 65,
          "$source": "DUMMY_LABEL.AI",
          "timestamp": "2020-02-08T09:48:58.219Z",
          "sentence": "VDM"
        },
        "draft": {
          "meta": {
            "description": "The draft of the vessel"
          },
          "value": {
            "current": 14.1
          },
          "$source": "DUMMY_LABEL.AI",
          "timestamp": "2020-02-08T09:48:58.219Z",
          "sentence": "VDM"
        },
        "aisShipType": {
          "meta": {
            "description": "The ais ship type see http://www.bosunsmate.org/ais/message5.php"
          },
          "value": {
            "id": 67,
            "name": "Passenger ship"
          },
          "$source": "DUMMY_LABEL.AI",
          "timestamp": "2020-02-08T09:48:58.219Z",
          "sentence": "VDM"
        }
      },
      "sensors": {
        "ais": {
          "fromBow": {
            "meta": {
              "description": "The distance from the bow to the sensor location along the longitudinal axis of the vessel (toward the stern)."
            },
            "value": 256,
            "$source": "DUMMY_LABEL.AI",
            "timestamp": "2020-02-08T09:48:58.219Z",
            "sentence": "VDM"
          },
          "fromCenter": {
            "meta": {
              "description": "The perpendicular distance from the longitudinal centerline of the vessel to the sensor location, +ve to starboard, -ve to port."
            },
            "value": 27.5,
            "$source": "DUMMY_LABEL.AI",
            "timestamp": "2020-02-08T09:48:58.219Z",
            "sentence": "VDM"
          },
          "class": {
            "value": "A",
            "$source": "DUMMY_LABEL.AI",
            "timestamp": "2020-02-08T09:48:58.219Z",
            "sentence": "VDM"
          }
        }
      },
      "navigation": {
        "destination": {
          "commonName": {
            "meta": {
              "description": "Common name of the Destination, eg 'Fiji', also used in ais messages"
            },
            "value": "OOI SILEN",
            "$source": "DUMMY_LABEL.AI",
            "timestamp": "2020-02-08T09:48:58.219Z",
            "sentence": "VDM"
          }
        }
      },
      "communication": {
        "callsignVhf": "PH510"
      }
    }
  },
  "self": "urn:mrn:imo:mmsi:246326000",
  "version": "0.1.0",
  "sources": {
    "DUMMY_LABEL": {
      "label": "DUMMY_LABEL",
      "type": "NMEA0183",
      "AI": {
        "talker": "AI",
        "sentences": {
          "VDM": "2020-02-08T09:48:58.219Z"
        }
      }
    }
  }
}
